# Generated by Django 5.0.4 on 2024-04-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, null=True)),
                ('author', models.CharField(max_length=90, null=True)),
                ('price', models.FloatField(null=True)),
                ('data_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
