# Generated by Django 5.0.4 on 2024-04-25 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='catecogy',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Historical Fiction', 'Historical Fiction'), ('hororr', 'horoor')], max_length=90, null=True),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pindeing', 'pinding'), ('delivered', 'delivered'), ('out of order', 'out of order')], max_length=90, null=True)),
                ('data_created', models.DateField(null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.customer')),
                ('tag', models.ManyToManyField(to='book.tag')),
            ],
        ),
    ]
